# Generated by Django 3.2.19 on 2023-05-16 05:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230516_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Время приготовлениядолжно быть не мене 1 минуты')], verbose_name='Время приготовления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='recipes.tags', verbose_name='Тег'),
        ),
    ]
