# Generated by Django 3.2.19 on 2023-05-16 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20230516_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsInShoppingCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_shopping_cart', models.BooleanField(verbose_name='Рецепт в покупках')),
            ],
            options={
                'verbose_name': 'Рецепт в покупках',
                'verbose_name_plural': 'Рецепты в покупках',
            },
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.ingredient', verbose_name='Название ингридиента'),
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.recipes', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='recipes.AmountIngredients', to='recipes.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='recipes.tags', verbose_name='Тег'),
        ),
        migrations.AddConstraint(
            model_name='amountingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_in_recipe'),
        ),
        migrations.AddField(
            model_name='isinshoppingcartmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipes.recipes', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='isinshoppingcartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='isinshoppingcartmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_is_in_shopping_cart'),
        ),
    ]
