# Generated by Django 3.2.19 on 2023-05-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230517_1552'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='isfavorite',
            name='unique_is_афмщкшеу',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure',
            new_name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='isfavorite',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='isinshoppingcartmodel',
            name='is_in_shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='isfavorite',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_is_favorite'),
        ),
    ]
