# Generated by Django 3.2.19 on 2023-06-06 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01', help_text='Дата публикации', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
