# Generated by Django 3.2.19 on 2023-05-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230516_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
