# Generated by Django 3.2.19 on 2023-06-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230601_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipe', through='recipes.AmountIngredients', to='recipes.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
    ]
