# Generated by Django 3.2.19 on 2023-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipe', through='recipes.AmountIngredients', to='recipes.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tags', verbose_name='Тег'),
        ),
    ]
